# Generated by Django 3.1.7 on 2021-04-07 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('skill1', models.CharField(blank=True, choices=[('seo', 'SEO'), ('web', 'Web Design'), ('content', 'Content Creation'), ('graphic', 'Graphic Design'), ('video', 'Video Editing'), ('other', 'Other'), ('none', 'None')], default='none', max_length=9, null=True)),
                ('skill2', models.CharField(blank=True, choices=[('seo', 'SEO'), ('web', 'Web Design'), ('content', 'Content Creation'), ('graphic', 'Graphic Design'), ('video', 'Video Editing'), ('other', 'Other'), ('none', 'None')], default='none', max_length=9, null=True)),
                ('skill3', models.CharField(blank=True, choices=[('seo', 'SEO'), ('web', 'Web Design'), ('content', 'Content Creation'), ('graphic', 'Graphic Design'), ('video', 'Video Editing'), ('other', 'Other'), ('none', 'None')], default='none', max_length=9, null=True)),
                ('qualification', models.CharField(blank=True, choices=[('high_school', 'High School'), ('university', 'University'), ('none', 'Prefer Not To Say')], default='none', max_length=15, null=True)),
                ('earnings', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=40, null=True)),
                ('sales', models.IntegerField(blank=True, default=0, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('orders', models.IntegerField(blank=True, default=0, null=True)),
                ('products', models.CharField(blank=True, max_length=1024, null=True)),
                ('product_count', models.IntegerField(blank=True, default=0, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('rank', models.IntegerField(blank=True, choices=[(1, 'Member'), (2, 'Recruit'), (3, 'Officer'), (4, 'Sergeant'), (5, 'General')], default=1, null=True)),
                ('user_type', models.IntegerField(blank=True, choices=[(1, 'Member'), (2, 'Freelancer')], default=1, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_website', models.CharField(blank=True, max_length=255, null=True)),
                ('member_since', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
