# Generated by Django 3.1.7 on 2021-04-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20210405_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='earnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='products',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='qualification',
            field=models.CharField(blank=True, choices=[('seo', 'SEO'), ('web', 'Web Design'), ('content', 'Content Creation'), ('graphic', 'Graphic Design'), ('video', 'Video Editing'), ('other', 'Other')], default='none', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.CharField(blank=True, choices=[('seo', 'SEO'), ('web', 'Web Design'), ('content', 'Content Creation'), ('graphic', 'Graphic Design'), ('video', 'Video Editing'), ('other', 'Other')], default='other', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
