# Generated by Django 3.1.7 on 2021-04-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20210405_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='personal_site',
            new_name='personal_website',
        ),
        migrations.AlterField(
            model_name='profile',
            name='qualification',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('university', 'University'), ('none', 'Prefer Not To Say')], default='none', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(blank=True, choices=[(1, 'Member'), (2, 'Recruit'), (3, 'Officer'), (4, 'Sergeant'), (5, 'General')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.CharField(blank=True, choices=[('seo', 'SEO'), ('web', 'Web Design'), ('content', 'Content Creation'), ('graphic', 'Graphic Design'), ('video', 'Video Editing'), ('other', 'Other')], default='other', max_length=9, null=True),
        ),
    ]
