# Generated by Django 3.1.7 on 2021-04-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20210405_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Member'), (2, 'Freelancer')], default=1, null=True),
        ),
    ]
