# Generated by Django 3.1.7 on 2021-04-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_profile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='orders',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='product_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill1',
            field=models.CharField(blank=True, choices=[('seo', 'SEO'), ('web', 'Web Design'), ('content', 'Content Creation'), ('graphic', 'Graphic Design'), ('video', 'Video Editing'), ('other', 'Other'), ('none', 'None')], default='none', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill2',
            field=models.CharField(blank=True, choices=[('seo', 'SEO'), ('web', 'Web Design'), ('content', 'Content Creation'), ('graphic', 'Graphic Design'), ('video', 'Video Editing'), ('other', 'Other'), ('none', 'None')], default='none', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill3',
            field=models.CharField(blank=True, choices=[('seo', 'SEO'), ('web', 'Web Design'), ('content', 'Content Creation'), ('graphic', 'Graphic Design'), ('video', 'Video Editing'), ('other', 'Other'), ('none', 'None')], default='none', max_length=9, null=True),
        ),
    ]
