# Generated by Django 3.1.7 on 2021-04-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_profile_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member_since',
            field=models.DateField(auto_now=True),
        ),
    ]
