# Generated by Django 3.1.7 on 2021-04-03 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
