# Generated by Django 3.1.7 on 2021-04-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='languages2',
            field=models.CharField(choices=[('False', 'None'), ('html', 'HTML'), ('css', 'CSS'), ('bootstrap', 'Bootstrap'), ('materialize', 'Materialize'), ('js', 'JavaScript'), ('jquery', 'jQuery'), ('node', 'Node'), ('react', 'React'), ('vue', 'Vue'), ('python', 'Python')], default='False', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='languages',
            field=models.CharField(choices=[('False', 'None'), ('html', 'HTML'), ('css', 'CSS'), ('bootstrap', 'Bootstrap'), ('materialize', 'Materialize'), ('js', 'JavaScript'), ('jquery', 'jQuery'), ('node', 'Node'), ('react', 'React'), ('vue', 'Vue'), ('python', 'Python')], default='False', max_length=20),
        ),
    ]
