# Generated by Django 3.1.7 on 2021-04-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210403_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='product',
            name='languages2',
        ),
        migrations.AddField(
            model_name='product',
            name='skill1',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('css', 'CSS'), ('bootstrap', 'Bootstrap'), ('materialize', 'Materialize'), ('js', 'JavaScript'), ('jquery', 'jQuery'), ('node', 'Node'), ('react', 'React'), ('vue', 'Vue'), ('python', 'Python'), ('django', 'Django'), ('sql', 'SQL'), ('writing', 'Writing'), ('seo', 'Search Engine Optimization'), ('graphics', 'Graphic Design'), ('videos', 'Video Editing')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='skill2',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('css', 'CSS'), ('bootstrap', 'Bootstrap'), ('materialize', 'Materialize'), ('js', 'JavaScript'), ('jquery', 'jQuery'), ('node', 'Node'), ('react', 'React'), ('vue', 'Vue'), ('python', 'Python'), ('django', 'Django'), ('sql', 'SQL'), ('writing', 'Writing'), ('seo', 'Search Engine Optimization'), ('graphics', 'Graphic Design'), ('videos', 'Video Editing')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='skill3',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('css', 'CSS'), ('bootstrap', 'Bootstrap'), ('materialize', 'Materialize'), ('js', 'JavaScript'), ('jquery', 'jQuery'), ('node', 'Node'), ('react', 'React'), ('vue', 'Vue'), ('python', 'Python'), ('django', 'Django'), ('sql', 'SQL'), ('writing', 'Writing'), ('seo', 'Search Engine Optimization'), ('graphics', 'Graphic Design'), ('videos', 'Video Editing')], max_length=20, null=True),
        ),
    ]
