# Generated by Django 3.1.7 on 2021-04-03 01:15

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210403_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='created_by_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='created_on',
            field=models.DateField(verbose_name=datetime.datetime(2021, 4, 3, 1, 14, 40, 553415)),
        ),
    ]
